### ISSUE TITLE
Wiki: TIRD link is broken?

### ISSUE THREAD

**Issue by shadiakiki1986** [oetiker/rrdtool-2.x#39]
On the wiki page [Portable Dataformat](https://github.com/oetiker/rrdtool-2.x/wiki/Portable-Dataformat#workaround) in section `workaround`, the TIRD link seems to be broken. I tried some searching on the internet to figure out what the updated link would be, but couldn't find anything.

**Comment by oetiker** [comment]
thanks. removed
